# ==============================
# GitHub Pages 极简配置 | GCY
# ==============================

title: GCY
description: Personal Blog
author: GCY

# GitHub 域名 (必须这样写)
url: "https://galen-coder.github.io/"
baseurl: ""

# 核心设置
theme: minima
permalink: /:title/
timezone: Asia/Shanghai

# 极简模式
show_excerpts: false
header_pages: []

# Markdown
markdown: kramdown
highlighter: rouge

# 忽略文件
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
